version: '3.5'

services:
    nginx:
      container_name: nginx
      build: requirements/nginx
      image: nginx:jonascim
      depends_on:
        - wordpress
      networks:
        - docker_network
      ports:
        - "443:443"
      volumes:
        - wordpress:/var/www/html
      restart: always
      env_file: .env

    mariadb:
      container_name: mariadb
      build: requirements/mariadb
      image: mariadb:jonascim
      networks:
        - docker_network
      volumes:
        - mariadb:/var/lib/mysql
      restart: always
      env_file: .env

    wordpress:
      container_name: wordpress
      build: requirements/wordpress
      image: wordpress:jonascim
      depends_on: 
        - mariadb
      networks:
        - docker_network
      volumes:
        - wordpress:/var/www/html
      restart: always
      env_file: .env

networks:
    docker_network:

volumes:
    wordpress:
      name: wordpress
      driver: local
      driver_opts:
        type: none
        device: /home/jonascim/data/html
        o: bind
    mariadb:
      name: mariadb
      driver: local
      driver_opts:
        type: none
        device: /home/jonascim/data/mysql
        o: bind
